name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build no defaults
      run: cargo build --verbose --no-default-features
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt
        toolchain: nightly
    - uses: actions-rust-lang/rustfmt@v1

  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy
    - name: Clippy
      run: cargo clippy --verbose -- -D warnings
